dist: xenial
language: python
python: 3.7.2
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - pytest --cmdopt=os.environ['LIBRARIES_API_KEY']  --cov --cov-append 
after_success:
  - coveralls
